create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  grammage text not null,
  composition text not null,
  width text not null,
  tag text,
  description text not null,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;

create policy "Produtos publicados sao visiveis publicamente"
  on public.products for select
  using (true);

create policy "Gestores autenticados podem publicar produtos"
  on public.products for insert
  to authenticated
  with check (true);
